### ISSUE TITLE
Configure all of the awaits in the simulator

### ISSUE THREAD

**Issue by bennage** [mspnp/iot-journey#178] opened 2015-07-01 00:43 UTC
We don't need to synchronize the context in the simulator. Let's add `.ConfigureAwait(false)` to all of the async calls. See 1f888d4bb8994122a20f0ebfbf0d4f30fa41375d for an example.

**Comment by lbrader** [comment] 2015-07-01 01:03
this is a duplicate of #171

**Closed** 2015-07-01 01:10 UTC
